// App.vue

<script setup lang="ts">
import Navbar from './components/Navbar.vue';
import Hero from './components/Hero.vue';
import FeatureGrid from './components/FeatureGrid.vue';
import WorkShowcase from './components/WorkShowcase.vue';
import Testimonials from './components/Testimonials.vue';
import Footer from './components/Footer.vue';
</script>

<template>
  <div class="min-h-screen flex flex-col overflow-x-hidden">
    <Navbar />
    <main class="flex-grow">
      <Hero />
      <FeatureGrid />
      <WorkShowcase />
      <Testimonials />
    </main>
    <Footer />
  </div>
</template>

// App.tsx

import React, { useState, useEffect } from 'react';
import Navbar from './components/Navbar';
import Hero from './components/Hero';
import FeatureGrid from './components/FeatureGrid';
import WorkShowcase from './components/WorkShowcase';
import Testimonials from './components/Testimonials';
import Footer from './components/Footer';

const App: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col overflow-x-hidden">
      <Navbar />
      <main className="flex-grow">
        <Hero />
        <FeatureGrid />
        <WorkShowcase />
        <Testimonials />
      </main>
      <Footer />
    </div>
  );
};

export default App;
