// components/Navbar.vue

<template>
  <nav class="fixed top-0 left-0 right-0 z-50 bg-gray-950/80 backdrop-blur-md border-b border-gray-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center h-20">
        <div class="flex items-center space-x-8">
          <a href="#" class="text-2xl font-bold tracking-tighter gradient-text">
            Dramaus
          </a>
          <div class="hidden md:flex space-x-6 text-sm font-medium text-gray-400">
            <a href="#features" class="hover:text-white transition-colors">工具集</a>
            <a href="#showcase" class="hover:text-white transition-colors">发现</a>
            <a href="#" class="hover:text-white transition-colors">教程</a>
            <a href="#" class="hover:text-white transition-colors">价格</a>
          </div>
        </div>
        <div class="flex items-center space-x-4">
          <button class="text-sm font-medium text-gray-400 hover:text-white transition-colors px-4 py-2">
            登录
          </button>
          <button class="text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-full transition-all shadow-lg shadow-indigo-500/20">
            免费注册
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>

// components/Navbar.tsx

import React from 'react';

const Navbar: React.FC = () => {
  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-gray-950/80 backdrop-blur-md border-b border-gray-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-20">
          <div className="flex items-center space-x-8">
            <a href="#" className="text-2xl font-bold tracking-tighter gradient-text">
              Dramaus
            </a>
            <div className="hidden md:flex space-x-6 text-sm font-medium text-gray-400">
              <a href="#features" className="hover:text-white transition-colors">工具集</a>
              <a href="#showcase" className="hover:text-white transition-colors">发现</a>
              <a href="#" className="hover:text-white transition-colors">教程</a>
              <a href="#" className="hover:text-white transition-colors">价格</a>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <button className="text-sm font-medium text-gray-400 hover:text-white transition-colors px-4 py-2">
              登录
            </button>
            <button className="text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-full transition-all shadow-lg shadow-indigo-500/20">
              免费注册
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
